global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "app_python"
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "app_go"
    static_configs:
      - targets: ["host.docker.internal:8080"]