apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: app-python.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-python-service
            port:
              number: 8000
  - host: app-golang.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-golang-service
            port:
              number: 8080