name: CI for Go app

on:
  push:
    paths:
      - "app_golang/**"
      - ".github/workflows/ci-golang.yaml"
  pull_request:
    paths:
      - "app_golang/**"
      - ".github/workflows/ci-golang.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.7"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('app_golang/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.63.4

      - name: Install dependencies
        run: |
          cd app_golang
          go mod tidy

      - name: Lint
        run: |
          cd app_golang
          golangci-lint run

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.7"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('app_go/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          cd app_golang
          go mod tidy

      - name: Test
        run: |
          cd app_golang
          go test

  snyk-check:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v4
      - name: Snyk Security Scan
        uses: snyk/actions/golang@master
        with:
          args: --skip-unresolved app_golang/
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: snyk-check
    env:
      DOCKER_IMAGE_NAME: "app_go"
      DOCKER_TAG: "latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd app_golang
          echo "Building Docker image: $DOCKER_IMAGE_NAME:$DOCKER_TAG"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:$DOCKER_TAG .

      - name: Push Docker image
        run: |
          echo "Pushing Docker image: $DOCKER_IMAGE_NAME:$DOCKER_TAG"
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:$DOCKER_TAG
